name: example
description: Demo of PrettyDiffText
publish_to: 'none'

version: 2.0.0

environment:
  sdk: ">=3.2.0-0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  pretty_diff_text:
    path: ../